[package]
name = "cxShare"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
toml = "0.8.19"
serde = { version = "1.0.215", features = ["derive"] }
diesel = "2.2.4"
